"""Synthetic-year robustness for the Phase-2 siting deliverable.

Competition scoring note (siting.md): "A design tuned only to the years you
trained on is penalised - robustness is the point"; the report asks how synthetic
years were used. Our shipped design was chosen by worst-of-5-REAL-years CF; this
job stress-tests it on many SYNTHETIC wind years generated by the kit's own
generator (Tier-1 AR(1) + Tier-0 block-bootstrap on the coarse-125 history), and
compares the chosen centre + layout against alternatives.

Outputs synthyear_result.json: per (centre, layout) CF distribution across
real-coarse years and synthetic years. All wind is coarse-125 IDW'd to the site
and sheared 125->170 m (alpha=0.11) exactly as the scorer does.
"""
from __future__ import annotations
import os, sys, json, argparse, time
os.environ.setdefault("PHASE2_DATA_ROOT", os.environ["SEAWINDS_PHASE2_DIR"])
KIT = "${SEAWINDS_ROOT}/kit_phase2/phase_2"
for p in (KIT, KIT + "/part0_dataset_setup", KIT + "/part2_siting"):
    sys.path.insert(0, p)
import numpy as np, pandas as pd, xarray as xr
if not hasattr(np, "trapezoid"):
    np.trapezoid = np.trapz
import glob
import wind_farm_simulator as wfs
import turbines_catalog as tc
import shear
import target_loader as tl
import synthetic_generator as sg

SHEAR = shear.power_law_factor(125, 170)
LAYOUT_JSON = "${SEAWINDS_ROOT}/scripts/results/siting_layout/layout_search.json"
P2 = os.environ["SEAWINDS_PHASE2_DIR"]; AROME_ROOT = f"{P2}/train/arome"
DIAM = 284.0

CENTRES = {
    "east_dogger_SHIPPED": (55.3173, 3.7662),
    "west_dogger": (55.10, 1.40),
    "baseline_kit": (53.5, 1.5),
}


def load_my_layout():
    """The SHIPPED layout. Defaults to the live submission file so this test always
    stress-tests what we actually send; set SYNTH_LAYOUT=grid to test the old grid."""
    if os.environ.get("SYNTH_LAYOUT", "shipped") == "shipped":
        sub = json.load(open("${SEAWINDS_ROOT}/"
                             "submission/siting/siting_submission.json"))
        return (np.asarray(sub["layout_x_m"], float),
                np.asarray(sub["layout_y_m"], float), "shipped_qd_irregular")
    d = json.load(open(LAYOUT_JSON))
    b = d["best"]
    return np.asarray(b["x"], float), np.asarray(b["y"], float), f"{b['nr']}x{b['nc']}_rot{b['rot']}_ar{b['ar']}"


def idw_site(lat, lon, U, V, clat, clon):
    """IDW (4 nearest coarse cells) grid -> site (ws@125, wd). U,V shape (T,C)."""
    d2 = (lat - clat) ** 2 + (lon - clon) ** 2
    order = np.argsort(d2)[:4]
    w = 1.0 / np.maximum(d2[order], 1e-9)
    w = w / w.sum()
    u = U[:, order] @ w
    v = V[:, order] @ w
    ws = np.hypot(u, v)
    wd = (270.0 - np.degrees(np.arctan2(v, u))) % 360.0
    return ws, wd


def cf_of(lay, ws125, wd, times):
    ws_hub = np.asarray(ws125, float) * SHEAR
    wd = np.asarray(wd, float)
    ok = np.isfinite(ws_hub) & np.isfinite(wd)
    wind = wfs.WindSeries(pd.DataFrame({"time": np.asarray(times)[ok], "ws": ws_hub[ok], "wd": wd[ok]}))
    res = wfs.simulate_year(lay, wind)
    return float(res.capacity_factor), float(res.wake_loss_fraction), float(res.aep_gwh)


def dist(cfs):
    a = np.asarray(cfs, float)
    return dict(mean=float(a.mean()), std=float(a.std()), min=float(a.min()),
                p05=float(np.percentile(a, 5)), max=float(a.max()), n=int(a.size),
                cv=float(a.std() / a.mean()) if a.mean() else float("nan"))


def fine_arome_cf(centres, lay, years):
    """AUTHORITATIVE fine-AROME (u125m/v125m) CF per centre per year, my layout.
    Reads each fine file once, extracts all centre cells. This is the metric the
    hidden scorer uses (coarse is edge-biased and only used for synth robustness)."""
    st = tl.load_static()
    cells = {}
    for cname, (clat, clon) in centres.items():
        d = (st.lat - clat) ** 2 + (st.lon - clon) ** 2
        iy, ix = np.unravel_index(np.nanargmin(d), d.shape)
        cells[cname] = (int(iy), int(ix), float(st.lat[iy, ix]), float(st.lon[iy, ix]))
    out = {c: {"cell": list(cells[c][2:]), "per_year": []} for c in centres}
    for yv in years:
        acc = {c: {"t": [], "u": [], "v": []} for c in centres}
        for f in sorted(glob.glob(f"{AROME_ROOT}/{yv}/arome_*.nc")):
            with xr.open_dataset(f) as ds:
                tt = pd.to_datetime(ds["time"].values)
                for cname, (iy, ix, _, _) in cells.items():
                    acc[cname]["u"].append(ds["u125m"].isel(y=iy, x=ix).values)
                    acc[cname]["v"].append(ds["v125m"].isel(y=iy, x=ix).values)
                    acc[cname]["t"].append(tt)
        for cname in centres:
            t = np.concatenate(acc[cname]["t"])
            u = np.concatenate(acc[cname]["u"]).astype(float)
            v = np.concatenate(acc[cname]["v"]).astype(float)
            ws = np.hypot(u, v)
            wd = (270.0 - np.degrees(np.arctan2(v, u))) % 360.0
            cf, wk, aep = cf_of(lay, ws, wd, t)
            out[cname]["per_year"].append(dict(year=yv, cf=cf, wake=wk, aep=aep))
    for cname in centres:
        out[cname]["dist"] = dist([r["cf"] for r in out[cname]["per_year"]])
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--years", default="2016,2017,2018,2019,2020")
    ap.add_argument("--n_ar", type=int, default=40)
    ap.add_argument("--n_boot", type=int, default=20)
    ap.add_argument("--fine", type=int, default=1, help="1=also compute authoritative fine-AROME CF per centre")
    ap.add_argument("--out", default="")
    a = ap.parse_args()
    t0 = time.time()
    years = [int(y) for y in a.years.split(",")]

    turb = tc.load_turbine("IEA_22MW")
    x, y, layout_cfg = load_my_layout()
    lay_opt = wfs.FarmLayout(x_m=x, y_m=y, turbine=turb)
    gx, gy = wfs.grid_layout(55, spacing_d=7.4, diameter_m=DIAM)
    lay_grid = wfs.FarmLayout(x_m=gx, y_m=gy, turbine=turb)
    LAYOUTS = {"opt_" + layout_cfg: lay_opt, "plain_grid_7.4D": lay_grid}

    print(f"[{time.time()-t0:.0f}s] loading coarse history {years} ...", flush=True)
    hist = sg.load_coarse_history(tuple(years))
    yr_of = np.array([t.year for t in hist.times])
    print(f"[{time.time()-t0:.0f}s] history T={hist.U.shape[0]} C={hist.U.shape[1]}; fitting AR ...", flush=True)
    armodel = sg.fit_ar_generator(hist)

    # Pre-generate synthetic years (grid-level, shared across centres/layouts)
    print(f"[{time.time()-t0:.0f}s] sampling {a.n_ar} AR + {a.n_boot} bootstrap years ...", flush=True)
    synth = []
    for s in range(a.n_ar):
        synth.append(("ar", s, sg.sample_ar_year(armodel, n_steps=1460, seed=s)))
    for s in range(a.n_boot):
        synth.append(("boot", s, sg.bootstrap_year(hist, block_days=14, n_steps=1460, seed=1000 + s)))

    out = {"shear_125_170": SHEAR, "layout_cfg": layout_cfg, "n_real_years": len(years),
           "n_ar": a.n_ar, "n_boot": a.n_boot, "results": {}}

    for cname, (clat, clon) in CENTRES.items():
        for lname, lay in LAYOUTS.items():
            # only run plain-grid comparison at the shipped centre (keep it cheap)
            if lname.startswith("plain") and cname != "east_dogger_SHIPPED":
                continue
            real_rows, synth_rows = [], []
            for yv in years:
                m = yr_of == yv
                ws, wd = idw_site(hist.lat, hist.lon, hist.U[m], hist.V[m], clat, clon)
                cf, wk, aep = cf_of(lay, ws, wd, hist.times[m])
                real_rows.append(dict(kind="real", tag=str(yv), cf=cf, wake=wk, aep=aep))
            for kind, s, sy in synth:
                ws, wd = idw_site(sy.lat, sy.lon, sy.U, sy.V, clat, clon)
                cf, wk, aep = cf_of(lay, ws, wd, sy.times)
                synth_rows.append(dict(kind=kind, tag=f"{kind}{s}", cf=cf, wake=wk, aep=aep))
            key = f"{cname}|{lname}"
            out["results"][key] = dict(
                centre=[clat, clon],
                real=dist([r["cf"] for r in real_rows]),
                synth=dist([r["cf"] for r in synth_rows]),
                real_rows=real_rows, synth_rows=synth_rows,
            )
            rd, sd = out["results"][key]["real"], out["results"][key]["synth"]
            print(f"[{time.time()-t0:.0f}s] {key:38s} real CF {rd['mean']*100:.2f}±{rd['std']*100:.2f} "
                  f"(min {rd['min']*100:.2f}) | synth CF {sd['mean']*100:.2f}±{sd['std']*100:.2f} "
                  f"(min {sd['min']*100:.2f}, p05 {sd['p05']*100:.2f})", flush=True)

    if a.fine:
        print(f"[{time.time()-t0:.0f}s] fine-AROME CF per centre ({years}) with opt layout ...", flush=True)
        fine = fine_arome_cf(CENTRES, lay_opt, years)
        out["fine_arome"] = fine
        for cname, fc in fine.items():
            fd = fc["dist"]
            print(f"[{time.time()-t0:.0f}s]   FINE {cname:22s} cell={fc['cell']} "
                  f"CF {fd['mean']*100:.2f}±{fd['std']*100:.2f} (min {fd['min']*100:.2f})", flush=True)

    outdir = a.out or os.environ.get("EXP_OUTPUT_DIR", ".")
    os.makedirs(outdir, exist_ok=True)
    dst = os.path.join(outdir, "synthyear_result.json")
    json.dump(out, open(dst, "w"), indent=1)
    print(f"[{time.time()-t0:.0f}s] wrote {dst}", flush=True)


if __name__ == "__main__":
    main()
